# Generated by Django 2.2.3 on 2019-08-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_no',
        ),
    ]
