# Generated by Django 2.2.3 on 2019-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('age', models.IntegerField(default=0)),
                ('php', models.BooleanField(default=False, verbose_name='Php')),
                ('django', models.BooleanField(default=False, verbose_name='Django')),
                ('laravel', models.BooleanField(default=False, verbose_name='Laravel')),
            ],
        ),
    ]
