# Generated by Django 2.2.3 on 2019-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ifeanyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ManyToManyField(to='cfmv.Developer')),
            ],
        ),
    ]
