# Generated by Django 2.2.3 on 2019-08-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmv', '0002_ifeanyi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='DeveloperSkill',
        ),
        migrations.DeleteModel(
            name='Ifeanyi',
        ),
    ]
